### PR TITLE
Files Formatted in backend directory.

### PR DESCRIPTION
**Pull request by aviiciii**
All files in the backend directory of the repository have been formatted with proper indentation using tabs for developers to easily select their own identation and understand the code better.

### CODE REVIEW

**Comment by Bhavesh38** [comment]
is backend running properly?

**Comment by aviiciii** [comment]
I am not sure how to run the backend. Could you please assist me?

**Comment by Bhavesh38** [comment]
> I am not sure how to run the backend. Could you please assist me?

terminal > cd into backend > npm i or npm i --legacy-peer-deps if first one doesn't works > nodemon server

**Comment by aviiciii** [comment]
@Bhavesh38 Here is the output of running the above command.
image

**Comment by Bhavesh38** [comment]
Run nodemon server

**Comment by aviiciii** [comment]
I get an output saying that the command is invalid.

image

**Comment by Bhavesh38** [comment]
Cd backend > nodemon server

**Comment by aviiciii** [comment]
@Bhavesh38 Yes, the backend is working fine.
image

**Comment by Bhavesh38** [comment]
Great

**Comment by aviiciii** [comment]
@Bhavesh38  Kindly note that I have only formatted the javascript codes and not edited any. Kindly accept the pull request.

**Comment by Bhavesh38** [comment]
> @Bhavesh38 Kindly note that I have only formatted the javascript codes and not edited any. Kindly accept the pull request.

accepted

**Pull request merged**
